---
title: "A Brief Introduction to Product-multinomial Likelihoods for Capture-mark-recapture Models"
format: html
number-sections: true
self-contained: true
number-depth: 2
editor: visual
---

::: {.hidden}
$$
\newcommand{\bo}{\boldsymbol{\omega}}
\newcommand{\bob}{\overline{\boldsymbol{\omega}}}
\newcommand{\bg}{\boldsymbol{\gamma}}
\newcommand{\bz}{\boldsymbol{0}}
\newcommand{\bx}{\boldsymbol{\xi}}
$$
:::

# Overview

Here we give a brief introduction to m-arrays and product-multinomial likelihoods for
single- and multi-state mark-recapture models. We recommend Williams et al. for a 
fuller treatment. 


# Single-state model

We'll start by considering a model with a single live state, so capture histories 
consist of ones and zeros indicating that the individual was or was not captured 
on the corresponding sampling occasion.

#### Constructing the m-array

The m-array summarises capture histories by the number of individuals that
are released on a given occasion and next recaptured at some later occasion, 
or never recaptured.  and @tbl-cjs_m-array illustrate an m-array for a study with five
individuals over four sampling occasions.

@tbl-cjs_ch presents the capture histories and their decomposition into segments 
spanning from each release to the next recapture, or to the end of the capture 
history if the individual is never recaptured after that release. For example, the 
history $1011$ describes an individual who was released on occasion $1$ and next 
recaptured on occasion $3$, then released on occasion $3$ and next recaptured on 
occasion $4$. Accordingly, $1011$ is split into two segments, $101*$ and $**11$, corresponding to these
two release-next recapture occasions. In contrast, an individual with history $0100$ 
was release on occasion $1$ but never recaptured, producing only one segment $*100$. We
use the wildcard $*$ to convey that a segment will be found in any capture history
containing the given pattern. For example, $**10$ is common to $1110$ and $0110$. 

| Complete capture history | Release (t=1) |  Release (t=2) |  Release (t=3) |
|:------:|:------:|:------:|:------:|
| $1011$ | $101*$ |   -    | $**11$ | 
| $1110$ | $11**$ | $*11*$ | $**10$ |
| $1001$ | $1001$ |   -    |   -    |
| $0110$ |   -    | $*11*$ | $**10$ |
| $0100$ |   -    | $*100$ |   -    |

: Some complete capture histories decomposed into release - next recapture segments  {#tbl-cjs_ch tbl-colwidths="[40,20,20,20]"}

@tbl-cjs_m-array presents the m-array for these data: the rows correspond to release occasions, and the columns to occasions of next recapture or never recaptured. The table entries contain the number of times the corresponding 
segment appeared in the capture histories. For example, the segment $*11*$ involving a release on occasion $2$ and
next recapture on occasion $3$ appears twice, hence the entry in the row labelled **2** and column labelled **3**. The 
reader is invited to check that every segment in @tbl-cjs_ch contributes to one of the entries in @tbl-cjs_m-array.


|  | 2 | 3 | 4 | Never |
|:------:|:------:|:------:|:------:| :------:|
| **1**    | $1$  | $1$  | $1$  | $0$ |
| **2**    |      | $2$  | $0$  | $1$ |
| **3**    |      |      | $1$  | $2$ |

: m-array summary of the capture histories in @tbl-cjs_ch {#tbl-cjs_m-array tbl-colwidths="[20,20,20,20,20]"}

#### Product-multinomial likelihood

Every individual released on a given occasion must be recaptured at some later occasion, or never recaptured.
The number of individuals realising these possibilities are distributed according to a multinomial distribution.
That is, each row $\mathbf{m}_i$ of the m-array $\mathbf{m}$ in @tbl-cjs_m-array are data for a multinomial distribution:
$$
\mathbf{m}_i \sim \text{multinomial}\left(\boldsymbol{\theta}_i\right) \hspace{5pt} \text{ for } \hspace{5pt}  i = 1, \cdots, T-1.
$$
The cell probabilities $\boldsymbol{\theta}_i$ are functions of survival and detection probabilities, and must sum to one. The likelihood for the full table is the product of these - hence the name product-multinomial likelihood. 

#### Calculating cell probabilities

To illustrate the calculation of probabilities for the multinomial distributions, we consider a model with 
time-dependent survival $\phi_t$ from time $t$ to $t+1$, and capture probabilities $p_t$ at time $t$. It's 
convenient to also define the probability of not being captured $q_1 = 1 - p_t$. Now the 
probability of each segment is calculated as follows:

- $\text{Pr}(11**) = \phi_1p_2$ since it involves surving from time $1$ to $2$ and being recaptured then,
- $\text{Pr}(*101) = \phi_2q_3 \cdot \phi_3p_4$, corresponding to survival from time $2$ to $3$, not being
recaptured at time $3$, then surviving from time $3$ to $4$ and being recaptured then,
- etc.

In @tbl-cjs_pm_probs we let $\xi_t$ be the probability of never being recaptured given release at time $t$.
These can be written in terms of the survival and detection probabilities if desired. In practice, we calculate 
them as one minus the probability of being recaptured at any later occasion, that is, as one minus
the sum of all the other entries in the same row.

|        | **2**     | **3**      | **4**     | **Never** |
|:------:|:-----:|:------:|:------:|:----:|
| **1**  | $\phi_1p_2$   |    $\phi_1q_2 \phi_2p_3$ |   $\phi_1q_2 \phi_2q_3 \phi_3p_4$   | $\xi_1$  |
| **2**  | $0$  |   $\phi_2p_3$ |  $\phi_2q_3 \phi_3p_4$   |  $\xi_2$  |
| **3**  | $0$    |     $0$ |   $\phi_3p_4$    | $\xi_3$  |

: Cell probabilities for the m-array in @tbl-cjs_m-array. {#tbl-cjs_pm_probs}

Each row of this table provides the cell probabilities, $\boldsymbol{\theta}_i$, for the
multinomial likelihood for the corresponding row, $\textbf{m}_i$, of the m-array.

# Multi-state models

The m-array for models with more than one (live) state is still based on release-next 
recapture segments but incorporates the state at release and recapture as well. If there
are $S$ states and $T$ capture occasions it consists of an $S(T-1) \times S(T-1) + 1$ array.

#### Constructing the m-array

For illustrative purposes we consider the case $S = 2$, so capture histories consist of zeros, 
ones and twos, indicating whether an individual was captured, and what state they were
in if captured. @tbl-ms_ch presents some example capture histories and the 
decomposition into release-next recapture (or release-never recapture) segments. 

| Complete capture history | Release (t=1) |  Release (t=2) |  Release (t=3) |
|:------:|:------:|:------:|:------:|
| $1021$ | $102*$ |   -    | $**21$ | 
| $2110$ | $21**$ | $*11*$ | $**10$ |
| $1001$ | $1001$ |   -    |   -    |
| $0210$ |   -    | $*21*$ | $**10$ |
| $0100$ |   -    | $*100$ |   -    |

: Some multi-state capture histories decomposed into release - next recapture segments  {#tbl-ms_ch tbl-colwidths="[40,20,20,20]"}

The m-array for these data are presented in @tbl-ms_m-array. Now there are
$S = 2$ rows for each release occasion and for each recapture occasion: the occasions
are typset in bold and the state at release and recapture in italics. The entries in 
the table once again represent the frequency of the corresponding segment in the data.

|  |  | 2 | 2 | 3 | 3 | 4 | 4 | Never |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|       |     | *1* | *2* | *1* | *2* | *1* | *2* |     |        
| **1** | *1* | $0$ | $0$ | $0$ | $1$ | $1$ | $0$ | $0$ |
| **1** | *2* | $1$ | $0$ | $0$ | $0$ | $0$ | $0$ | $0$ |
| **2** | *1* |     |     | $1$ | $0$ | $0$ | $0$ | $1$ |
| **2** | *2* |     |     | $1$ | $0$ | $0$ | $0$ | $0$ |
| **3** | *1* |     |     |     |     | $0$ | $0$ | $2$ |
| **3** | *2* |     |     |     |     | $1$ | $0$ | $0$ |

: m-array summary of the capture histories in @tbl-ms_ch. Occasions are in bold, states in italic. {#tbl-ms_m-array tbl-colwidths="[5,5,10,10,10,10,10,10,10]"}

#### Product-multinomial likelihood

As before, the totals in each row are distributed according to a multinomial distribution.
However, the cell probabilities for these multinomial distributions are easiest to 
calculate in $S \times S$ blocks using matrix multiplication.  

#### Calculating cell probabilities

For concreteness, suppose our two states represent sites, and our model includes
site- and time-varying survival ($\phi_{i,t}$) and detection ($p_{i,t}$) probabilities, 
and time-invariant movement probabilitues ($m_{i,j}$). 

Consider the probability that an individual released from site $1$ at time $t$ is 
next recaptured at site $2$ at time $t+2$. Because we do not know where it was at 
time $t+1$, we have to average over the possibilities, yielding
$$
\underbrace{\phi_{1,t}m_{1,1}q_{1,t+1} \cdot \phi_{1,t+1}m_{1,2}p_{2,t+2}}_{\text{at site } 1 \text{ at time } t+1 } +
\underbrace{\phi_{1,t}m_{1,2}q_{2,t+1} \cdot \phi_{2,t+1}m_{2,2}p_{2,t+2}}_{\text{at site } 2 \text{ at time } t+1 }
$$
We also have to calculate the analogous probabilities for the other three combinations of site at release and next recapture. It turns out all the probabilities can be calculated at once as the product of suitable matrices:
$$
\begin{pmatrix}
\phi_{1,t}m_{1,1} & \phi_{1,t}m_{1,2} \\
\phi_{2,t}m_{2,1} & \phi_{2,t}m_{2,2} 
\end{pmatrix}
\begin{pmatrix}
q_{1,t+1} & 0 \\
0 & q_{2,t+1} 
\end{pmatrix}
\begin{pmatrix}
\phi_{1,t+1}m_{1,1} & \phi_{1,t+1}m_{1,2} \\
\phi_{2,t+1}m_{2,1} & \phi_{2,t+1}m_{2,2} 
\end{pmatrix}
\begin{pmatrix}
p_{1,t+2} & 0 \\
0 & p_{2,t+2} 
\end{pmatrix}.
$$
The $i,j^{\text{th}}$ entry of the resulting matrix is the probability that an individual released from site $i$ at time $t$ is next recaptured at site $j$ at time $t+2$ (we invite the reader to verify this). Therefore this matrix contains the cell probabilities for the $2 \times 2$ block of @tbl-ms_m-array corresponding to release occasion $1$ and next recapture occasion $3$.

The blocks corresponding to other release and recapture occasions follow a similar pattern. Define 
$$
\bg_t = \begin{pmatrix}
\phi_{1,t}m_{1,1} & \phi_{1,t}m_{1,2} \\
\phi_{2,t}m_{2,1} & \phi_{2,t}m_{2,2} 
\end{pmatrix}, \hspace{10pt}
\bob_t = \begin{pmatrix}
q_{1,t} & 0 \\
0 & q_{2,t} 
\end{pmatrix} \hspace{5pt} \text{ and } \hspace{5pt}
\bo_t = \begin{pmatrix}
p_{1,t} & 0 \\
0 & p_{2,t} 
\end{pmatrix}. 
$$

Then the cell probabilities for the m-array can be as a matrix defined in blocks as

|        | **2**     | **3**      | **4**     | **Never** |
|:------:|:-----:|:------:|:------:|:----:|
| **1**  | $\bg_1 \bo_2$  | $\bg_1 \bob_2 \bg_2 \bo_3$ |   $\bg_1 \bob_2 \bg_2 \bob_3 \bg_3 \bo_4$   | $\bx_1$ |
| **2**  | $\bz$          |        $\bg_2 \bo_3$       |            $\bg_2 \bob_3\bg_3 \bo_4$        | $\bx_2$ |
| **3**  | $\bz$          |           $\bz$            |                 $\bg_3 \bo_4$               | $\bx_3$ |

As in the single-state case, the $\bx_i$ are determined by the constraint that each row sum to one (but now they are column vectors of length $2$). The cell probabilities for each multinomial distribution are contained in the rows of this matrix.